sonar.projectKey=johannesroesch_oidc-client
sonar.organization=johannesroesch

sonar.sources=includes,oidc-client.php
sonar.tests=tests

sonar.php.coverage.reportPaths=coverage.xml
sonar.php.tests.reportPath=test-results.xml

sonar.exclusions=vendor/**,dist/**,assets/**
sonar.coverage.exclusions=tests/**
